#!/usr/bin/perl --

# For macOS - quick vi session to edit text on clipboard.

# 1. Copy some text to your clipboard.
# 2. Cmd-tab to your terminal and run vv.
# 3. Make your changes and then :wq.
# 4. Now your changed text is in the clipboard.

use strict;
use warnings;

my $tempFile = qq{/tmp/vv_clipboard_editor_${$}.txt};

my $removeNewline = qq{| /usr/bin/perl -p -e 's/.\$//s'};
$removeNewline = ''; # Haven't gotten this working, and it's not a big deal.

system("pbpaste > $tempFile");
system(qq{/usr/bin/vim $tempFile});
system(qq{cat ${tempFile} ${removeNewline} | pbcopy});
unlink $tempFile;

